const FONTS = [
    {name: "monofont", id: "monofont", val: 0},
    {name: "Pangolin", id: "'Pangolin', cursive", val: 1},
    {name: "Bad Script", id: "'Bad Script', cursive", val: 2},
    {name: "Comfortaa", id: "'Comfortaa', cursive", val: 3},
    {name: "Cormorant SC", id: "'Cormorant SC', serif", val: 4},
    {name: "Didact Gothic", id: "'Didact Gothic', sans-serif", val: 5},
    {name: "Exo 2", id: "'Exo 2', sans-serif", val: 6},
    {name: "Forum", id: "'Forum', cursive", val: 7},
    {name: "Kelly Slab", id: "'Kelly Slab', cursive", val: 8},
    {name: "Kurale", id: "'Kurale', serif", val: 9},
    {name: "Lobster", id: "'Lobster', cursive", val: 10},
    {name: "Lobster Two", id: "'Lobster Two', cursive", val: 11},
    {name: "Lora", id: "'Lora', serif", val: 12},
    {name: "Marck Script", id: "'Marck Script', cursive", val: 13},
    {name: "Merriweather Sans", id: "'Merriweather Sans', sans-serif", val: 14},
    {name: "Merriweather", id: "'Merriweather', serif", val: 15},
    {name: "Neucha", id: "'Neucha', cursive", val: 16},
    {name: "Noto Serif", id: "'Noto Serif', serif", val: 17},
    {name: "Open Sans", id: "'Open Sans', sans-serif", val: 18},
    {name: "Open Sans Condensed", id: "'Open Sans Condensed', sans-serif", val: 19},
    {name: "Oswald", id: "'Oswald', sans-serif", val: 20},
    {name: "Philosopher", id: "'Philosopher', sans-serif", val: 21},
    {name: "Play", id: "'Play', sans-serif", val: 22},
    {name: "Playfair Display", id: "'Playfair Display', serif", val: 23},
    {name: "Poiret One", id: "'Poiret One', cursive", val: 24},
    {name: "Press Start 2P", id: "'Press Start 2P', cursive", val: 25},
    {name: "Roboto Condensed", id: "'Roboto Condensed', sans-serif", val: 26},
    {name: "Roboto Slab", id: "'Roboto Slab', serif", val: 27},
    {name: "Rubik", id: "'Rubik', sans-serif", val: 28},
    {name: "Rubik Mono One", id: "'Rubik Mono One', sans-serif", val: 29},
    {name: "Ruslan Display", id: "'Ruslan Display', cursive", val: 30},
    {name: "Russo One", id: "'Russo One', sans-serif", val: 31},
    {name: "Underdog", id: "'Underdog', cursive", val: 32},
    {name: "Amatic SC", id: "'Amatic SC', cursive", val: 33},
    {name: "Caveat", id: "'Caveat', cursive", val: 34},
    {name: "Jura", id: "'Jura', sans-serif", val: 35},
    {name: "Andika", id: "'Andika', sans-serif", val: 36},
    {name: "Literata", id: "'Literata', serif", val: 37},
    {name: "Poiret One", id: "'Poiret One', cursive", val: 38},
    {name: "Fira Sans Extra Condensed", id: "'Fira Sans Extra Condensed', sans-serif", val: 39},
    {name: "Montserrat", id: "'Montserrat', sans-serif", val: 40},
]
